default_stages: [commit]
# default_stages: [commit, manual]  # for 2xxxxx


default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # rev: v3.2.0
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        # stages: [commit]  # the base config also includes manual, 2adding makes it skip the hook
        files: ^app/
      - id: end-of-file-fixer
        stages: [commit]  # the base config also includes manual, 2adding makes it skip the hook
      - id: check-yaml
        stages: [commit]  # the base config also includes manual, 2adding makes it skip the hook
      - id: check-added-large-files
        args: ["--maxkb=1500"]
        # stages: [commit]  # the base config also includes manual, 2comment and hook will run

  - repo: https://github.com/pycqa/pylint
    # rev: 2.13.9
    rev: v2.14.4
    hooks:
    - id: pylint
      files: ^(app/)
      args: ["--rcfile=pylintrc"]
      stages: [manual]
      # stages: [commit, manual]


  - repo: https://github.com/psf/black
    rev: 22.3.0
    # rev: 22.6.0
    hooks:
      - id: black
        files: ^(app/)
        # files: ^(app/|tests/)
        args: ["--check"]
        language_version: python3
        stages: [manual]
        # stages: [commit, manual]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
        # types: [file, yaml]
        # entry: yamllint --strict -f parsable
        args: ["-d", "relaxed", "."]
        stages: [manual]
        # stages: [commit, manual]

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v2.5.1
  #   hooks:
  #     - id: prettier
  #       # stages: [commit]
