repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: mixed-line-ending
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
#   - repo: https://github.com/pre-commit/mirrors-prettier
#     hooks:
#       - id: pytest
#         name: Check pytest unit tests pass
#         entry: pipenv run pytest
#         pass_filenames: false
#         language: system
#         types: [python]
#       - id: mypy
#         name: Check mypy static types match
#         entry: pipenv run mypy . --ignore-missing-imports
#         pass_filenames: false
#         language: system
#         types: [python]


# ---
# default_language_version:
#   python: python3

# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     # rev: v4.1.0
#     hooks:
#       - id: end-of-file-fixer
#       - id: mixed-line-ending
#       - id: trailing-whitespace
  
#   - repo: https://github.com/pre-commit/mirrors-prettier
#     # rev: v2.5.1
#     hooks:
#       - id: prettier
#         stages: [commit]