name: pre-commit-auto-update-run

on:
  workflow_call:

jobs:
  pre_commit_auto_update_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install precommit
      run: pip install pre-commit

    - name: list files
      run: |
        pwd
        ls -latr
        cat ./.pre-commit-config.yaml
      shell: bash

    - name: Run pre-commit-autoupdate
      id: precommit-autoupdate
      run: |
        pre-commit autoupdate
        if [ -n "$(git status --porcelain)" ]; then
          echo "::set-output name=updated::true"
        else
          echo "::set-output name=updated::false"
        fi

    - name: Commit new changes
      if: steps.precommit-autoupdate.updated == 'true'
      run: |
        git config --global user.name "GHA"
        git config --global user.email "dexy004@gmail.com"
        git commit -am "pre-commit autoupdate at $(date --utc +'%Y-%m-%d %H:%MZ')"
        git log -1

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure
  
    - name: Create PR
      # if: success()
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "chore: pre-commit autoupdate"
        title: pre-commit autoupdate
        body: Automated pull request for pre-commit autoupdate
        branch: pre-commit-autoupdate
        base: main
        token: ${{ secrets.GITHUB_TOKEN }}
