name: PyLint Run

on:
  workflow_call:
    inputs:
      app_src_dir:
        description: >
          The application source directory.
        required: true
        type: string
      
      rc_file:
        description: >
          The link to configuration file.
            (default: pylintrc)
        required: false
        type: string
        default: pylintrc
      
      app_test_dir:
        description: >
          The application test directory.
            (default: tests)
        required: false
        type: string
        default: tests

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Pylint
      run: pip install pylint
    
    - name: list files
      run: |
        pwd
        ls -latr
      shell: bash

    - name: Run Pylint
      run: pylint --rcfile=${{ inputs.rc_file}} ${{ inputs.app_src_dir}} ${{ inputs.app_test_dir}}
