name: PyLint Run

on:
  workflow_call:
    inputs:
      app_src_dir:
        required: true
        type: string
      
      rc_file:
        required: false
        type: string
        default: pylintrc
      
      app_test_dir:
        required: false
        type: string
        default: tests

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Pylint
      run: pip install pylint
    
    - name: list files
      run: |
        pwd
        ls -latr
      shell: bash

    # - name: Run Pylint
    #   run: pylint --rcfile=${{ inputs.rc_file}} ${{ inputs.app_src_dir}} ${{ inputs.app_test_dir}}
    
    - name: Run black
      run: black --check ${{ inputs.app_src_dir}}
