name: Mark stale issues and pull requests

on:
  # schedule:
  #   - cron: "21 4 * * *"
  workflow_call:
    inputs:
      # days_before_stale:
      #   description: >
      #     The number of days old an issue or a pull request 
      #     can be before marking it stale. Set to -1 to never 
      #     mark issues or pull requests as stale automatically.
      #   required: false
      #   type: number
      #   default: 90

      stale_pr_message:
        description: >
          The message to post on the pull request when tagging it. If none provided, will not mark pull requests stale. 
        type: string
        default: "This pull request has become stale and will be closed automatically within a period of ${{ inputs.days_before_pr_close }}."
        required: false
      
      stale_pr_label:
        description: >
          The label to apply when a pull request is stale. 
        type: string
        default: "no-pr-activity"
        required: false
      
      days_before_pr_stale:
        description: >
          The number of days old a pull request can be before marking it stale. 
          Set to -1 to never mark pull requests as stale automatically. 
          Override "days-before-stale" option regarding only the pull requests.'
        type: number
        default: 90
        required: false
      
      days_before_pr_close:
        description: >
          The number of days to wait to close a pull request after it being marked stale. Set to -1 to never close stale pull requests. 
          Override "days-before-close" option regarding only the pull requests.
        type: number
        default: 1
        required: false

jobs:
  stale:

    permissions:
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Mark stale PRs
        id: stale_pr
        uses: actions/stale@v7
        with:
          # The message to post on the pull request when tagging it. If none provided, will not mark pull requests stale.
          stale-pr-message: ${{ inputs.stale_pr_message }}
          # The label to apply when a pull request is stale.
          stale-pr-label: ${{ inputs.stale_pr_label }}
          # The number of days old a pull request can be before marking it stale. Set to -1 to never mark pull requests as stale automatically. 
          # Override "days-before-stale" option regarding only the pull requests.'
          days-before-pr-stale: ${{ inputs.days_before_pr_stale }}
          # The number of days to wait to close a pull request after it being marked stale. Set to -1 to never close stale pull requests.
          # Override "days-before-close" option regarding only the pull requests.
          days-before-pr-close: ${{ inputs.days_before_pr_close }}
          
          # #  Issues
          # # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
          # stale-issue-message: 'This issue has become stale and will be closed automatically within a period of time. Sorry about that.'
          # # The label to apply when an issue is stale.
          # stale-issue-label: 'no-issue-activity'
          # # The number of days old an issue or a pull request can be before marking it stale. 
          # # Set to -1 to never mark issues or pull requests as stale automatically.
          # days-before-stale: ${{ inputs.days_before_stale }}


      # - name: Notify
      #   if: success()
      #   run: |
      #     echo stale_pr.