name: Test Workflow

on:
  workflow_run:
    workflows:
      - Linting
    types:
      - completed

jobs:
  test-workflow-black:
    name: workflow-black
    uses: ./.github/workflows/black.yml
    with:
        app_src_dir: app
