name: pre-commit-run

on:
  workflow_call:
    
jobs:
  tox_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install tox
      run: pip install tox

    - name: list files
      run: |
        pwd
        ls -latr
 
      shell: bash

    - name: Run tox39
      run: tox -e py39
